### ISSUE TITLE
Installation fails - status set to notworking in one week

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/shuri_ynh#1]
Hello,

Your app failed to install on our CI, hence it will be set at notworking status in one week unless installation is fixed.

You can find the complete log here
https://ci-apps.yunohost.org/jenkins/job/shuri%20(Community)/6/console

Don't hesitate to join our Apps packaging room on XMPP (apps@conference.yunohost.org) for help!

The YunoHost Apps Group

**Comment by frju365** [comment]
fixed !
